version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    container_name: kafka-course-zookeeper-1
    user: "root"
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-course-kafka-1
    networks:
      - broker-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafka-course-kafdrop-1
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "19000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
  
  payment:
    image: wesleimb/payment-service:1.0.1
    networks:
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - "8002:8002"
    environment:
      KAFKA_HOST: kafka:29092  

  consumer:
    image: wesleimb/json-consumer:1.0.1
    networks:
      - broker-kafka
    depends_on:
      - kafka
      - payment
    environment:
      KAFKA_HOST: kafka:29092

networks:
  broker-kafka:
    driver: bridge
